name: Frontend Linting

on:
  push:
    branches:
      - 'fe/*'
  pull_request:
    branches:
      - 'fe/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: './frontend/.nvmrc'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run linter
        run: yarn lint
        working-directory: ./frontend
